// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtkl1cL79ZGSnxyDoW59jaAxrNnexktrY',
    appId: '1:577723131085:android:cdf31e60d4a15a0a14b584',
    messagingSenderId: '577723131085',
    projectId: 'tstore-cbb4a',
    storageBucket: 'tstore-cbb4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBCJuIlqa9PaoZIQdIHFMkOo6HT3YnA1o',
    appId: '1:577723131085:ios:28e23e82e6286e0b14b584',
    messagingSenderId: '577723131085',
    projectId: 'tstore-cbb4a',
    storageBucket: 'tstore-cbb4a.appspot.com',
    androidClientId: '577723131085-lgtgdbq8p1f3qp65fls5412j2ogvthl7.apps.googleusercontent.com',
    iosClientId: '577723131085-ri0nnct38ae25kt09nvsmdr981e2jgab.apps.googleusercontent.com',
    iosBundleId: 'com.example.tstore',
  );
}
